### PR TITLE
Fake HTTP_HOST and SERVER_NAME

### PR DESCRIPTION
**Pull request by Valicek1**
This change is [Reviewable](https://reviewable.io/reviews/mrtnzlml/testbench/31)

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Thank, but [tests are failing now](https://travis-ci.org/mrtnzlml/testbench/builds/148521725). It's probably going to be more complicated to implement this feature...

**Comment by Valicek1** [comment]
Yes, but the tests were failing at build 192, so it was broken before my PR (test 193). Build 194 passed again, so the problem was probbably fixed - any way to rerun Travis tests?

**Comment by mrtnzlml** [comment]
Build 192 is for `transactional-db-tests` branch - not master. Now it's rebuilding but I don't believe it's going to be solution. I will solve this PR later (in my free time).

**Comment by mrtnzlml** [comment]
Merged, thanks.

**Pull request closed without merging**
